name: 07 - Using Expressions

on:
  push:
  workflow_dispatch:
    inputs:
      debug:
        description: 'Enable debug mode'
        required: false
        type: boolean
        default: false


jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: "[debug] Print start-up data"
        if: ${{ inputs.debug == true }}
        run: |
          echo "Triggered by: ${{ github.event_name }}"
          echo "Branch: ${{ github.ref }}"
          echo "Commit SHA: ${{ github.sha }}"
          echo "Runner OS: ${{ runner.os }}"
      - name: "[debug] Print when triggered from master"
        if: ${{ inputs.debug == true && github.ref == 'refs/heads/master' }}
        run: echo "I was triggered from master branch"
      - name: "Greeting"
        run: echo "Hello, world"